/**
 * Vimbox-rooms
 * Beta
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WorkbookHomeworkInfo } from './workbookHomeworkInfo';
import { WorkbookTestInfo } from './workbookTestInfo';


export interface WorkbookWithLastRoomDate {
    id?: number;
    lessonId?: number;
    lessonRevId?: number;
    homework?: WorkbookHomeworkInfo;
    test?: WorkbookTestInfo;
}
