/**
 * Vimbox-rooms
 * Beta
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface WorkbookTestInfo {
    id?: number;
    score?: number;
    completeness?: number;
    isCompletedTogether?: boolean;
    /**
     * Тип теста ={lesson, revise, adaptive, general}
     */
    type?: string;
    finishedAt?: string;
}
